### PR TITLE
Docker infrastructure for Eureka and ActiveMQ

### PR DESCRIPTION
**Pull request by viswaramamoorthy**
Docker compose and shell script to launch Eureka and ActiveMQ as docker containers

### CODE REVIEW

**Comment by awasum** [comment]
@viswaramamoorthy, @myrle-krantz  What is the status of this?

**Comment by viswaramamoorthy** [comment]
I have no idea. 

Other bigger question I had was whether anyone can successfully run demo-server and all services. I have not heard anything on that. I could not run demo-server and all of the services it launches. With external infrastructure it helps significantly and that is this PR. Needs more fixes overall.

**Comment by awasum** [comment]
To answer your question, I can run demo server with all the services and launch the web app successfully. Major problems with fact that the process is resource intensive. Demo server does not really run in the background and on each restart, you need to drop the databases on both cassandra and MySQL else you get a tenant already exists exception.

Please let me take some time and test out the new PR to see if the Docker Infra thing is optional as per @myrle-krantz request.

**Comment by viswaramamoorthy** [comment]
@awasum Assuming you are able launch demo server with embedded Eureka etc,. are not seeing exception indicating Eureka heart beat failure? when this exception happens, Junit shuts down after attempting to launch couple of services.

**Comment by awasum** [comment]
I have 32GB server. Enough memory, but a less memory intensive approach will be better.

**Comment by myrle-krantz** [comment]
Hi all,

I responded to this PR on the mailing list here:
https://lists.apache.org/thread.html/9b1c5250c131e49bba1842c7b8afbc6469e1ff1ca094b1b9f3fd686b@%3Cdev.fineract.apache.org%3E

...I haven't heard back on my requested changes.

As to being able to run the demo-server, I ran it again today to verify.  I have no troubles whatsoever getting it up.  This is not the computer I originally programmed anything on; I forked and pulled fineract-cn just like anyone else would. : o)

One possible source of error: you need to set the demoserver.provision environment variable to make sure things get provisioned before further setup is called.  I believe that should be made the default, but perhaps that's your problem?

Best Regards,
Myrle

**Comment by myrle-krantz** [comment]
Viswa, your problem with eureka may be related to the fact that you've set registerWithEureka to false in your application.yml file.  I pulled your PR, and had the same difficulties.  Deleting that file made it work again.

**Comment by viswaramamoorthy** [comment]
@myrle-krantz Hello, regarding PR review comment "@ Before can be run multiple times for a class", I agree when there are many tests in a SpringBootTest class. With a single "@ Test" in ServiceRunner, will Junit @ Before annotated method can run multiple times? May be I am missing something here. I want understand it and change.

Regarding application.yml file introduced in demo server, it is required because without that demo server attempts to register with Eureka and below error seen from demo server. Also, is demo server discoverable? My assumption is that it is not and hence turn off Eureka registration from demo server. But services will continue to register because they are discoverable.

**Error from demo-server** 
07:48:20.737 [DiscoveryClient-HeartbeatExecutor-0] ERROR c.netflix.discovery.DiscoveryClient - DiscoveryClient_UNKNOWN/localhost:-1 - was unable to send heartbeat!
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:111)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:832)
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

My earlier comments about Eureka issues are really about heart beat errors in provisioner, identity etc. Below is a sample error from identify.log. I am not sure how you or @awasum not seeing this error. Is it because of embedded server that masks this issue? Below error will ultimately lead to wrong service status and affect service discoverability...

**Eureka heart beat error from Identity**
07:50:52.172 [DiscoveryClient-HeartbeatExecutor-0] ERROR c.netflix.discovery.DiscoveryClient - DiscoveryClient_IDENTITY-V1/localhost:identity-v1:2021 - was unable to send heartbeat!
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:111)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89)
	at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:832)
	at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1396)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
07:50:53.191 [DiscoveryClient-HeartbeatExecutor-0] ERROR c.n.d.s.t.d.RedirectingEurekaHttpClient - Request execution error

**Comment by myrle-krantz** [comment]
Hey Viswa,

The DiscoveryClient is used by the demo-server to wait until a service is "up".  We poll at increasing intervals until we see that the service in question is registered with Eureka.  It's a more reliable way to wait until a service is up than just guessing how long it will take and programming purely with fixed length sleeps.  The relevant line can be found here: https://github.com/apache/fineract-cn-demo-server/blob/develop/src/main/java/io/mifos/dev/ServiceRunner.java#L298

As to what I'm looking for with respect to the test rules:  I've programmed it out for you so that you can see it.  Here:
```
  public static final ExternalResource EUREKA_FOR_TEST = new RunExternalResourceConditionally(
      new EurekaForTest(),
      System.getProperty("external.infrastructure") == null);
```
You'll have to pull fineract-cn-test because that's where I added the "RunExternalResourceConditionally" test rule.

If you're looking for general information about the useage of TestRules and ExternalResources in junit, here's a good tutorial: https://carlosbecker.com/posts/junit-rules/

Best Regards,
Myrle

**Comment by viswaramamoorthy** [comment]
Hi Myrtle,

Regarding your DiscoveryClient comment, I have seen it. The reason, I have introduced application.yml in demo-server with EurekaRegistration turned off, to really address exceptions seen in demo-server that I noted in my above comment. It is to address that and DiscoveryClient checks were retained in my PR as is. From I have tested, EurekaRegistration need not be done in demo-server but still you could Autowire/use DiscoveryClient to check if other services are up. Someone can verify if the exceptions that I noted above are seen or not. Also, when this is deployed in a VM, it gives a common deployed environment to check on these. For now, my Eureka exception related comments can be parked and monitored.

On the ClassRule suggestions and changes, I am not sure if utilizing Junit to launch services is really a good practice. Junit is largely for testing purposes. Although demo-server is not for production deployment (my hope is this :-) ), it still looks awkward to utilize it for demo-server. I was really questioning defining standard practice surrounding a technology which probably does not fit in this case. 

In any case, if you have already done change in fineract-cn-test, I assume that I need to pull that and make minor changes in demo-server to adopt it, test and update this PR for merge. Is my understanding correct?

**Comment by myrle-krantz** [comment]
Hey Viswa,

as I said, your change breaks the demo-server for me.  Until you've remedied that, I can't merge it.

As to your points about JUnit and testing: the demo-server evolved from an integration test which I used to debug the provisioning code and the interaction between identity and provisioner.  I copied that code into the demo-server originally so that a UI developer could deploy the system locally to code against it. 
He needed it to test fims against a running backend.  It is *not* intended as a production-ready deployment.  It took me weeks to get the interplay between the various pieces right, and I never would have achieved it without the demo-server.

I provided it to the project since the provisioning code is non-trivial, and most people trying to use it will need a starting point.  This is a microservices architecture.  The whole framework was never intended for a single system deployment, so of course the demo-server isn't something anyone would ever use in this form in production.  Further, most companies will have very different needs, and will want to change various aspects of the provisioning including, but not limited to which services are provisioned, what roles and users are created, which users originate the events produced by rhythm, and what tenants are created.

Your understanding is correct: "You'll have to pull fineract-cn-test because that's where I added the "RunExternalResourceConditionally" test rule."

Greets,
Myrle

**Comment by viswaramamoorthy** [comment]
@myrle-krantz I have adopted ClassRule changes to start Embedded Eureka and ActiveMQ. Please note that I was able to verify demo server start up after starting Docker based Eureka, ActiveMQ, MariaDB and Cassandra. It works consistently.

I could not verify embedded Eureka and ActiveMQ as it always fails. I am not sure that errors I see are related to processor or memory - because the error is at very early stage 

Below is the error
Time: 57.92
There was 1 failure:
1) io.mifos.dev.ServiceRunner
org.springframework.boot.context.embedded.tomcat.ConnectorStartFailedException: Connector configured to listen on port 8761 failed to start

Anyway, if you could verify embedded infrastructure with my PR, please merge

**Comment by myrle-krantz** [comment]
Hey Viswa: Your PR has conflicts, probably resulting from the package rename from mifos to apache.  I didn't want to put that rename off any longer, because I was afraid I would end up causing conflicts in more PRs if I continued to delay.  My apologies for the inconvenience.

But even with those conflicts resolved, I still can't merge your PR because it breaks the demo-server the way I use it.  I believe tests with docker infra can be an interesting approach, but I don't want to lose the one click startup.  If you still want to move this forward, you'll need to figure out which one of your changes breaks the embedded startup.

I repeat: my demo-server works just fine without your changes.  With your changes it does not work.  The important diff seems to be your addition of the application.yml file.  If I remove that, my demo-server works.

**Comment by myrle-krantz** [comment]
Closing for inactivity.

**Pull request closed without merging**
